In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv("csv/water_potability_limpo.csv")
X = df.drop("Potability", axis=1)
y = df["Potability"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# C: Inverso da força de regularização (menores = mais penalização)
# penalty: Tipo de penalidade (L1 tenta zerar variáveis inúteis, L2 encolhe todas)
# solver: Algoritmos de otimização adequados para L1 e L2
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga'] # Estes suportam tanto L1 quanto L2
}

# modelo base mantendo o balanceamento
lr_base = LogisticRegression(class_weight='balanced', random_state=42, max_iter=2000)

#  a busca
lr_grid = GridSearchCV(
    estimator=lr_base,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

print(" (LR) ")
lr_grid.fit(X_train, y_train)

melhor_lr = lr_grid.best_estimator_
y_pred = melhor_lr.predict(X_test)

print("\n Melhores parâmetros encontrados para a LR:")
print(lr_grid.best_params_)

print("\n    Relatório de Classificação (LR Otimizada)    ")
print(classification_report(y_test, y_pred))

print("\n    Matriz de Confusão (LR Otimizada)    ")
print(confusion_matrix(y_test, y_pred))

 (LR) 
Fitting 5 folds for each of 24 candidates, totalling 120 fits


/home/francion/trabalho-final-tc/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/francion/trabalho-final-tc/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/home/francion/trabalho-final-tc/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ra


 Melhores parâmetros encontrados para a LR:
{'C': 0.001, 'penalty': 'l1', 'solver': 'saga'}

    Relatório de Classificação (LR Otimizada)    
              precision    recall  f1-score   support

           0       0.61      1.00      0.76       400
           1       0.00      0.00      0.00       256

    accuracy                           0.61       656
   macro avg       0.30      0.50      0.38       656
weighted avg       0.37      0.61      0.46       656


    Matriz de Confusão (LR Otimizada)    
[[400   0]
 [256   0]]


/home/francion/trabalho-final-tc/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/francion/trabalho-final-tc/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/franci

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv("csv/water_potability_limpo.csv")
X = df.drop("Potability", axis=1)
y = df["Potability"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# n_estimators: Número de árvores na floresta
# max_depth: Limita a profundidade para evitar o sobreajuste (overfitting) no ruído
# min_samples_split: Número mínimo de amostras necessárias para dividir um nó interno
# class_weight: Estratégias de pesos para lidar com o desbalanceamento das classes
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_base = RandomForestClassifier(random_state=42)

#  buscador automático f
rf_grid = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

print(" (RF) ")
rf_grid.fit(X_train, y_train)

melhor_rf = rf_grid.best_estimator_
y_pred = melhor_rf.predict(X_test)

print("\n Melhores parâmetros encontrados para o RF:")
print(rf_grid.best_params_)

print("\n    Relatório de Classificação (RF Otimizado) ")
print(classification_report(y_test, y_pred))

print("\n    Matriz de Confusão (RF Otimizado)    ")
print(confusion_matrix(y_test, y_pred))

 (RF) 
Fitting 5 folds for each of 72 candidates, totalling 360 fits

 Melhores parâmetros encontrados para o RF:
{'class_weight': 'balanced', 'max_depth': None, 'min_samples_split': 10, 'n_estimators': 300}

    Relatório de Classificação (RF Otimizado) 
              precision    recall  f1-score   support

           0       0.69      0.77      0.73       400
           1       0.56      0.46      0.50       256

    accuracy                           0.65       656
   macro avg       0.62      0.61      0.61       656
weighted avg       0.64      0.65      0.64       656


    Matriz de Confusão (RF Otimizado)    
[[307  93]
 [139 117]]


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

df = pd.read_csv("csv/water_potability_limpo.csv")

# limites aceitáveis de potabilidade
df['ph_ideal'] = df['ph'].apply(lambda x: 1 if 6.5 <= x <= 8.5 else 0)
df['chloramines_seguro'] = df['Chloramines'].apply(lambda x: 1 if x <= 4.0 else 0)
df['sulfate_ideal'] = df['Sulfate'].apply(lambda x: 1 if x <= 250.0 else 0)
df['solids_seguro'] = df['Solids'].apply(lambda x: 1 if x <= 1000.0 else 0) # Limite comum de TDS

X = df.drop("Potability", axis=1)
y = df["Potability"]

# 3. Dividir em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

peso_classe = len(y_train[y_train == 0]) / len(y_train[y_train == 1])


xgb_base = XGBClassifier(
    random_state=42, 
    eval_metric='logloss',
    scale_pos_weight=peso_classe # peso equilibrado exato
)

# focada na curva ROC-AUC 
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1],
    'subsample': [0.8, 1.0]
}

# testar as combinações 
xgb_grid = GridSearchCV(
    estimator=xgb_base,
    param_grid=param_grid,
    cv=5,
    scoring='roc_auc', 
    n_jobs=-1,
    verbose=1
)

print(" (XGB) ")
xgb_grid.fit(X_train, y_train)

melhor_xgb = xgb_grid.best_estimator_
y_pred = melhor_xgb.predict(X_test)
y_prob = melhor_xgb.predict_proba(X_test)[:, 1] 

print("\n     Relatório de Classificação Definitivo    ")
print(classification_report(y_test, y_pred))

print("\n     Matriz de Confusão Definitiva     ")
print(confusion_matrix(y_test, y_pred))

print(f"\nROC-AUC Score: {roc_auc_score(y_test, y_prob):.4f}")

 (XGB) 
Fitting 5 folds for each of 24 candidates, totalling 120 fits

     Relatório de Classificação Definitivo    
              precision    recall  f1-score   support

           0       0.69      0.74      0.72       400
           1       0.55      0.48      0.51       256

    accuracy                           0.64       656
   macro avg       0.62      0.61      0.62       656
weighted avg       0.64      0.64      0.64       656


     Matriz de Confusão Definitiva     
[[298 102]
 [132 124]]

ROC-AUC Score: 0.6463


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv("csv/water_potability_limpo.csv")
X = df.drop("Potability", axis=1)
y = df["Potability"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# max_depth: controla o crescimento para evitar que ele decore o ruído
# min_samples_split: força os nós a serem maiores antes de dividirem
# class_weight: testa o balanceamento padrão vs balanceamento por subamostra
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'class_weight': ['balanced', 'balanced_subsample']
}

etc_base = ExtraTreesClassifier(random_state=42)

# focada no melhor F1-Score da Classe 1
etc_grid = GridSearchCV(
    estimator=etc_base,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

print(" (ETC)")
etc_grid.fit(X_train, y_train)

melhor_etc = etc_grid.best_estimator_
y_pred = melhor_etc.predict(X_test)

print("\nMelhores parâmetros encontrados para o ETC:")
print(etc_grid.best_params_)

print("\n    Relatório de Classificação (ETC Otimizado)    ")
print(classification_report(y_test, y_pred))

print("\n    Matriz de Confusão (ETC Otimizado)    ")
print(confusion_matrix(y_test, y_pred))